<a href="https://colab.research.google.com/github/iamkishore0/Python_Libraries/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Import numpy and name as np
import numpy as np

In [4]:
#Create a list and convert that to ndarray
a = [1,2,3,4]
print(type(a))

b = np.array(a)
type(b)

<class 'list'>


numpy.ndarray

In [7]:
#Create an ndarray and check dimention
c = np.array([1,2,3])
print(c)
print(type(c))
c.ndim

[1 2 3]
<class 'numpy.ndarray'>


1

In [9]:
#Multi-Dimentional arrays 
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

print(d.ndim)
print(e.ndim)

2
3


In [14]:
#Shape of arrays
f = np.array([[1,2],[3,4]])
g = np.array([[[1,2],[3,4],[5,6]]])
h = np.array([[1,2,3],[2,3,4]])
i = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[7,8,9,1,2],[2,3,4,5,6]]]])

print(f.shape)
print(g.shape)
print(h.shape)
print(i.shape)

(2, 2)
(1, 3, 2)
(2, 3)
(1, 1, 4, 5)


In [12]:
#Data type
f.dtype

dtype('int64')

In [18]:
#Slicing
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

#Access 6
print(a[0, 5])
#Access 10
print(a[1, 2])

6
10


In [20]:
#Manipulation
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

#replace 7 with 9
a[0, 6] = 9

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  9]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Matrix - convert an array to matrix

a = np.array([1,2])
print(type(a))

b = np.matrix(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [27]:
#Maths with arrays
x = np.array([1,2,3,4,5])

print(x+2)
print(x-1)
print(x*2)
print(x/2)
print(np.cos(x))
print(np.tan(x))

[3 4 5 6 7]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [28]:
#DataType mapping and memory - bitsize
my_arr = np.array([(1,2),(3,4)], dtype=[('a', '<i1'),('b','<i8')])

a = (my_arr[0][0])
b = (my_arr[0][1])
c = (my_arr[1][0])
d = (my_arr[1][1])

print(a)
print(b)
print(c)
print(d)

print(type(a))
print(type(b))
print(type(c))
print(type(d))

1
2
3
4
<class 'numpy.int8'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.int64'>
