<a href="https://colab.research.google.com/github/iamkishore0/Python_Libraries/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
#Import numpy and name as np
import numpy as np

In [32]:
#Create a list and convert that to ndarray
a = [1,2,3,4]
print(type(a))

b = np.array(a)
type(b)

<class 'list'>


numpy.ndarray

In [33]:
#Create an ndarray and check dimention
c = np.array([1,2,3])
print(c)
print(type(c))
c.ndim

[1 2 3]
<class 'numpy.ndarray'>


1

In [34]:
#Multi-Dimentional arrays and print dimentions using ndim
x = np.array([1,2,3,4,5])
d = np.array([[1,2,3],[4,5,6]])
e = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

print(x.ndim)
print(d.ndim)
print(e.ndim)

1
2
3


In [35]:
#Shape of arrays - Rows and Columns
f = np.array([[1,2],[3,4]])
g = np.array([[[1,2],[3,4],[5,6]]])
h = np.array([[1,2,3],[2,3,4]])
i = np.array([[[[1,2,3,4,5],[4,5,6,7,8],[7,8,9,1,2],[2,3,4,5,6]]]])

print(f.shape)
print(g.shape)
print(h.shape)
print(i.shape)

(2, 2)
(1, 3, 2)
(2, 3)
(1, 1, 4, 5)


In [36]:
#Data type
f.dtype

dtype('int64')

In [37]:
#item size
f.itemsize

8

In [38]:
#byte size
f.nbytes

32

In [39]:
#Create an array with 2 columns,3 rows and data filled with zeros, ones
x = np.zeros((2,3))
print(x) 

y = np.ones((2,3))
print(y)

#Multi-dimentional
z = np.zeros((1,3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [40]:
#Data fill with full
x = np.full((2,3), 99)
print(x)

[[99 99 99]
 [99 99 99]]


In [41]:
# Fill with random numbers
v = np.random.rand(3,4)
print(v)

[[0.14054879 0.58067175 0.05625173 0.19109448]
 [0.36178853 0.46546086 0.70056339 0.58103782]
 [0.34802815 0.93615298 0.38030941 0.03484766]]


In [42]:
#Slicing
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

#Access 6
print(a[0, 5])
#Access 10
print(a[1, 2])

6
10


In [43]:
#Manipulation
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

#replace 7 with 9
a[0, 6] = 9

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  9]
 [ 8  9 10 11 12 13 14]]


In [44]:
#Matrix - convert an array to matrix

a = np.array([1,2])
print(type(a))

b = np.matrix(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [45]:
#identity matrix
z = np.identity(5)
print(z)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
#Maths with arrays
x = np.array([1,2,3,4,5])

print(x+2)
print(x-1)
print(x*2)
print(x/2)
print(np.cos(x))
print(np.tan(x))

[3 4 5 6 7]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [47]:
#DataType mapping and memory - bitsize
my_arr = np.array([(1,2),(3,4)], dtype=[('a', '<i1'),('b','<i8')])

a = (my_arr[0][0])
b = (my_arr[0][1])
c = (my_arr[1][0])
d = (my_arr[1][1])

print(a)
print(b)
print(c)
print(d)

print(type(a))
print(type(b))
print(type(c))
print(type(d))

1
2
3
4
<class 'numpy.int8'>
<class 'numpy.int64'>
<class 'numpy.int8'>
<class 'numpy.int64'>
